#!/bin/bash

backup_directories=$(ls $HOME/*/ | grep -o -E "Backup-[0-9]{4}-[0-9]{2}-[0-9]{2}")

previous_backup_time_seconds=0
previous_backup_directory=""

if [[ $backup_directories ]]
then
  	previous_backup_directory=$(echo "$backup_directories" | tail -1)
  	previous_backup_date=$(echo "$previous_backup_directory" | grep -o -E "[0-9]{4}-[0-9]{2}-[0-9]{2}")
  	previous_backup_time_seconds=$(date -d $previous_backup_date +%s)
fi

current_date=`date +%Y-%m-%d`
current_time_seconds=$(date -d $current_date +%s)

backup_directory_path=""
new_backup_directory_flag=false

if [[ $current_time_seconds -gt $previous_backup_time_seconds+7*24*60*60 ]]
then
  	backup_directory_path="$HOME/Backup-$current_date"
  	mkdir $backup_directory_path
  	new_backup_directory_flag=true
else
  	backup_directory_path="$HOME/$previous_backup_directory"
fi

source_directory_path="$HOME/source"

if [[ ! -d "$source_directory_path" ]]
then
	echo "Error: source directory is not found. It must be [$source_directory_path]"
	exit 1
fi

report_file_path="$HOME/backup-report"

cd "$source_directory_path"

source_files=$(find . -type f)

if [[ $new_backup_directory_flag == true ]]
then
	echo "$backup_directory_path was created at $current_time" >> $report_file_path
	for filename in $source_files
		do
    			cp --parents "$filename" "$backup_directory_path/"
			echo "$filename was copied to $backup_directory_path at $current_date" >> $report_file_path
  		done
else
	for filename in $source_files
		do
    			if [[ -e "$backup_directory_path/$filename" ]]
			then
				old_size=$(stat -c%s "$backup_directory_path/$filename")
				new_size=$(stat -c%s "$source_directory_path/$filename")
      
      				if [[ $old_size -ne $new_size ]]; then
        				mv "$backup_directory_path/$filename" "$backup_directory_path/$filename.$current_date"
        				cp "$source_directory_path/$filename" "$backup_directory_path/$filename"
        
        				echo "$filename was renamed to $filename.$current_date $current_date" >> $report_file_path
        				echo "$filename was copied to $backup_directory_path at $current_date" >> $report_file_path
      				fi
    			else
      				cp --parents "$filename" "$backup_directory/"
      				echo "$filename was copied to $backup_directory_path at $current_date" >> $report_file_path
    			fi
  		done
fi
